feat(skeleton): TEDI-Ready component Skeleton #167
TEHIK-EE/tedi-design-system pull request #252
Opened 2024-10-25 07:00 UTC by airikej

2024-10-28 06:50 UTC, mart-sessman requested changes

2024-10-28 06:50 UTC, mart-sessman commented on libs/react-components/src/tedi/components/skeleton/skeleton.stories.tsx
> +            style: { '--loader-skeleton-color': '#ff0000' } as React.CSSProperties,
Kasutada variable-t HEX väärtuse asemel.

2024-10-28 06:50 UTC, mart-sessman commented on libs/react-components/src/tedi/components/skeleton/skeleton.stories.tsx
> +            style: { '--loader-skeleton-color': '140 99 10' } as React.CSSProperties,
Siin ka kasutada variable-t.

2024-11-06 14:11 UTC, RometPastak approved these changes

2024-11-06 14:14 UTC, mart-sessman approved these changes

2024-11-12 06:57 UTC, merged